name: Deploy

on:
  push:
    branches:
      - master  # Chỉ thực hiện deploy khi có thay đổi trên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@192.168.1.100 << 'EOF'
          docker pull tdq11111/backend_nodejs
          docker run -d --name backend_nodejs -p 8080:8080 tdq11111/backend_nodejs
          EOF
