
name: Docker Hub Build Trigger

on:
  push:
    branches:
      - main  # Chỉ trigger khi có push vào nhánh main
  workflow_dispatch:  # Cho phép chạy workflow bằng cách thủ công từ GitHub Actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |name: Deploy

on:
  push:
    branches:
      - main  # Chỉ thực hiện deploy khi có thay đổi trên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker-compose pull
          docker-compose up -d
          EOF

          docker build -t tdq11111/backend_nodejs .
          docker push tdq11111/backend_nodejs
