name: CICD

on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1
              id: buildx

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v2
              id: docker_build
              with:
                  context: ./
                  file: ./Dockerfile
                  builder: ${{ steps.buildx.outputs.name}}
                  push: true
                  tags: tdq11111/backend_nodejs

            - name: verify
              run: echo ${{ steps.docker_build.outputs.digest}}

    deploy:
        needs: build
        runs-on: [aws-ec2]
        steps:
            - name: Pull image from docker hub
              run: docker pull tdq11111/backend_nodejs
            - name: Delete old container
              run: docker rm -f nodejs-app-container
            - name: Run docker container
              run: docker run -d -p 8080:8080 --name nodejs-app-container tdq11111/backend_nodejs
